/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CryptoAsset = IDL.Record({
  'name' : IDL.Text,
  'usdValue' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const Time = IDL.Int;
export const TargetLevel = IDL.Record({
  'priceLevel' : IDL.Float64,
  'source' : IDL.Text,
  'confidenceScore' : IDL.Float64,
  'levelType' : IDL.Text,
  'timestamp' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PredictionOutcome = IDL.Record({
  'predictedValue' : IDL.Float64,
  'actualValue' : IDL.Float64,
  'confidence' : IDL.Float64,
  'outcome' : IDL.Text,
});
export const AssetOutcomes = IDL.Record({
  'assetSymbol' : IDL.Text,
  'predictionOutcomes' : IDL.Vec(PredictionOutcome),
});
export const AlertConfig = IDL.Record({
  'updated_at' : Time,
  'criticalAlertDays' : IDL.Vec(IDL.Nat),
  'minVolumeThreshold' : IDL.Float64,
  'highPriorityAlertTypes' : IDL.Vec(IDL.Text),
  'maxAlertFrequency' : IDL.Nat,
  'minIntensityThreshold' : IDL.Float64,
});
export const CapitalFlow = IDL.Record({
  'marketImpact' : IDL.Float64,
  'flowIntensity' : IDL.Float64,
  'pnlRatio' : IDL.Float64,
  'timestamp' : Time,
  'amount' : IDL.Float64,
  'fromAsset' : CryptoAsset,
  'toAsset' : CryptoAsset,
});
export const ModelPerformance = IDL.Record({
  'performanceScore' : IDL.Float64,
  'confidenceCorrelation' : IDL.Float64,
  'validationResults' : IDL.Vec(IDL.Text),
  'deviation' : IDL.Float64,
  'predictions' : IDL.Vec(PredictionOutcome),
  'assetSymbol' : IDL.Text,
  'modelName' : IDL.Text,
  'timestamp' : Time,
  'validationTime' : IDL.Float64,
  'accuracy' : IDL.Float64,
});
export const PriceTicker = IDL.Record({
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'preferences' : IDL.Opt(IDL.Text),
});
export const ConfidenceMetrics = IDL.Record({
  'improvementRatio' : IDL.Float64,
  'averageConfidence' : IDL.Float64,
  'assetSymbol' : IDL.Text,
  'accuracyImprovement' : IDL.Float64,
  'confidenceAccuracyCorrelation' : IDL.Float64,
});
export const ConfluenceZone = IDL.Record({
  'indicators' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
  'intensity' : IDL.Float64,
});
export const RegionalFlow = IDL.Record({
  'velocity' : IDL.Float64,
  'toRegion' : IDL.Nat,
  'fromRegion' : IDL.Nat,
  'volume' : IDL.Float64,
  'timestamp' : Time,
  'correlations' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  'intensity' : IDL.Float64,
});
export const DayFlowRange = IDL.Record({
  'startTime' : Time,
  'endTime' : Time,
  'flowData' : IDL.Vec(RegionalFlow),
});
export const InstitutionalAlert = IDL.Record({
  'intensityChange' : IDL.Float64,
  'type' : IDL.Text,
  'alertId' : IDL.Nat,
  'volumeChange' : IDL.Float64,
  'timestamp' : Time,
  'regionId' : IDL.Nat,
});
export const PerformanceSummary = IDL.Record({
  'averageAccuracy' : IDL.Float64,
  'totalPredictions' : IDL.Nat,
  'validatedPredictions' : IDL.Nat,
  'assetSymbol' : IDL.Text,
  'averageDeviation' : IDL.Float64,
  'lowestPerformer' : IDL.Text,
  'highestPerformer' : IDL.Text,
  'validationTime' : IDL.Float64,
});
export const PredictiveProjection = IDL.Record({
  'trend' : IDL.Text,
  'asset' : CryptoAsset,
  'targetLevels' : IDL.Vec(TargetLevel),
  'confidenceLevel' : IDL.Float64,
  'precision' : IDL.Float64,
  'timeHorizon' : IDL.Nat,
});
export const RecoveryAsset = IDL.Record({
  'rsi' : IDL.Float64,
  'supports' : IDL.Vec(IDL.Float64),
  'patternType' : IDL.Text,
  'volume' : IDL.Float64,
  'openInterest' : IDL.Float64,
  'isMomentumBreakout' : IDL.Bool,
  'isInstitutionalEntry' : IDL.Bool,
  'recoveryStrength' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const Region = IDL.Record({
  'flowRatio' : IDL.Float64,
  'name' : IDL.Text,
  'volume' : IDL.Float64,
  'capitalFlow' : IDL.Float64,
  'countryCodes' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
  'regionId' : IDL.Nat,
  'intensity' : IDL.Float64,
  'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
});
export const RegionalFlowConfig = IDL.Record({
  'name' : IDL.Text,
  'velocityMultiplier' : IDL.Float64,
  'countryCodes' : IDL.Vec(IDL.Text),
  'intensityMultiplier' : IDL.Float64,
  'regionId' : IDL.Nat,
  'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
});
export const RegionalCorrelation = IDL.Record({
  'correlationStrength' : IDL.Float64,
  'timestamp' : Time,
  'regionId' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const RegionalCryptoAsset = IDL.Record({
  'marketCap' : IDL.Float64,
  'name' : IDL.Text,
  'liquidity' : IDL.Float64,
  'regionalVolume' : IDL.Float64,
  'usdValue' : IDL.Float64,
  'timestamp' : Time,
  'regionId' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const RegionalMetric = IDL.Record({
  'value' : IDL.Float64,
  'timestamp' : Time,
  'metricType' : IDL.Text,
  'regionId' : IDL.Nat,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCapitalFlow' : IDL.Func(
      [
        IDL.Text,
        CryptoAsset,
        CryptoAsset,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'addConfluenceZone' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Float64],
      [],
      [],
    ),
  'addInstitutionalAlert' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'addModelPerformance' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'addPredictionOutcome' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'addPredictiveProjection' : IDL.Func(
      [
        IDL.Text,
        CryptoAsset,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Opt(IDL.Vec(TargetLevel)),
      ],
      [],
      [],
    ),
  'addRecoveryAsset' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Vec(IDL.Float64),
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'addRegion' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Tuple(IDL.Float64, IDL.Float64)],
      [],
      [],
    ),
  'addSummary' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addValidationResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearDailyAnalysis' : IDL.Func([IDL.Text], [], []),
  'clearOldStats' : IDL.Func([], [], []),
  'clearValidationResults' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAggregatedPredictions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AssetOutcomes)],
      ['query'],
    ),
  'getAlertConfig' : IDL.Func([IDL.Nat], [AlertConfig], ['query']),
  'getAllFlows' : IDL.Func([], [IDL.Vec(CapitalFlow)], ['query']),
  'getAllModelPerformances' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ModelPerformance)],
      ['query'],
    ),
  'getCachedPrices' : IDL.Func([], [IDL.Vec(PriceTicker)], ['query']),
  'getCachedSymbols' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCapitalFlow' : IDL.Func([IDL.Text], [CapitalFlow], ['query']),
  'getConfidenceMetrics' : IDL.Func([IDL.Text], [ConfidenceMetrics], ['query']),
  'getConfluenceZone' : IDL.Func([IDL.Text], [ConfluenceZone], ['query']),
  'getDayFlowRange' : IDL.Func([IDL.Nat, IDL.Nat], [DayFlowRange], ['query']),
  'getInstitutionalAlerts' : IDL.Func(
      [],
      [IDL.Vec(InstitutionalAlert)],
      ['query'],
    ),
  'getInterpretation' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'direction' : IDL.Text,
          'summary' : IDL.Text,
          'intensity' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getModelPerformance' : IDL.Func(
      [IDL.Text, IDL.Text],
      [ModelPerformance],
      ['query'],
    ),
  'getPerformanceSummary' : IDL.Func(
      [IDL.Text],
      [PerformanceSummary],
      ['query'],
    ),
  'getPredictionOutcomes' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PredictionOutcome)],
      ['query'],
    ),
  'getPredictiveProjection' : IDL.Func(
      [IDL.Text],
      [PredictiveProjection],
      ['query'],
    ),
  'getRecoveryAsset' : IDL.Func([IDL.Text], [RecoveryAsset], ['query']),
  'getRegion' : IDL.Func([IDL.Nat], [Region], ['query']),
  'getRegionConfigs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, RegionalFlowConfig))],
      ['query'],
    ),
  'getRegionCoordinates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Tuple(IDL.Float64, IDL.Float64)))],
      ['query'],
    ),
  'getRegionalCorrelations' : IDL.Func(
      [],
      [IDL.Vec(RegionalCorrelation)],
      ['query'],
    ),
  'getRegionalCryptoAsset' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [RegionalCryptoAsset],
      ['query'],
    ),
  'getRegionalFlowConfig' : IDL.Func(
      [IDL.Nat],
      [RegionalFlowConfig],
      ['query'],
    ),
  'getRegionalMetric' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [RegionalMetric],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getValidationResults' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getValidationState' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCriticalAlertDay' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], ['query']),
  'printVolumeChanges' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDirection' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CryptoAsset = IDL.Record({
    'name' : IDL.Text,
    'usdValue' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const Time = IDL.Int;
  const TargetLevel = IDL.Record({
    'priceLevel' : IDL.Float64,
    'source' : IDL.Text,
    'confidenceScore' : IDL.Float64,
    'levelType' : IDL.Text,
    'timestamp' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PredictionOutcome = IDL.Record({
    'predictedValue' : IDL.Float64,
    'actualValue' : IDL.Float64,
    'confidence' : IDL.Float64,
    'outcome' : IDL.Text,
  });
  const AssetOutcomes = IDL.Record({
    'assetSymbol' : IDL.Text,
    'predictionOutcomes' : IDL.Vec(PredictionOutcome),
  });
  const AlertConfig = IDL.Record({
    'updated_at' : Time,
    'criticalAlertDays' : IDL.Vec(IDL.Nat),
    'minVolumeThreshold' : IDL.Float64,
    'highPriorityAlertTypes' : IDL.Vec(IDL.Text),
    'maxAlertFrequency' : IDL.Nat,
    'minIntensityThreshold' : IDL.Float64,
  });
  const CapitalFlow = IDL.Record({
    'marketImpact' : IDL.Float64,
    'flowIntensity' : IDL.Float64,
    'pnlRatio' : IDL.Float64,
    'timestamp' : Time,
    'amount' : IDL.Float64,
    'fromAsset' : CryptoAsset,
    'toAsset' : CryptoAsset,
  });
  const ModelPerformance = IDL.Record({
    'performanceScore' : IDL.Float64,
    'confidenceCorrelation' : IDL.Float64,
    'validationResults' : IDL.Vec(IDL.Text),
    'deviation' : IDL.Float64,
    'predictions' : IDL.Vec(PredictionOutcome),
    'assetSymbol' : IDL.Text,
    'modelName' : IDL.Text,
    'timestamp' : Time,
    'validationTime' : IDL.Float64,
    'accuracy' : IDL.Float64,
  });
  const PriceTicker = IDL.Record({
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'preferences' : IDL.Opt(IDL.Text),
  });
  const ConfidenceMetrics = IDL.Record({
    'improvementRatio' : IDL.Float64,
    'averageConfidence' : IDL.Float64,
    'assetSymbol' : IDL.Text,
    'accuracyImprovement' : IDL.Float64,
    'confidenceAccuracyCorrelation' : IDL.Float64,
  });
  const ConfluenceZone = IDL.Record({
    'indicators' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
    'intensity' : IDL.Float64,
  });
  const RegionalFlow = IDL.Record({
    'velocity' : IDL.Float64,
    'toRegion' : IDL.Nat,
    'fromRegion' : IDL.Nat,
    'volume' : IDL.Float64,
    'timestamp' : Time,
    'correlations' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
    'intensity' : IDL.Float64,
  });
  const DayFlowRange = IDL.Record({
    'startTime' : Time,
    'endTime' : Time,
    'flowData' : IDL.Vec(RegionalFlow),
  });
  const InstitutionalAlert = IDL.Record({
    'intensityChange' : IDL.Float64,
    'type' : IDL.Text,
    'alertId' : IDL.Nat,
    'volumeChange' : IDL.Float64,
    'timestamp' : Time,
    'regionId' : IDL.Nat,
  });
  const PerformanceSummary = IDL.Record({
    'averageAccuracy' : IDL.Float64,
    'totalPredictions' : IDL.Nat,
    'validatedPredictions' : IDL.Nat,
    'assetSymbol' : IDL.Text,
    'averageDeviation' : IDL.Float64,
    'lowestPerformer' : IDL.Text,
    'highestPerformer' : IDL.Text,
    'validationTime' : IDL.Float64,
  });
  const PredictiveProjection = IDL.Record({
    'trend' : IDL.Text,
    'asset' : CryptoAsset,
    'targetLevels' : IDL.Vec(TargetLevel),
    'confidenceLevel' : IDL.Float64,
    'precision' : IDL.Float64,
    'timeHorizon' : IDL.Nat,
  });
  const RecoveryAsset = IDL.Record({
    'rsi' : IDL.Float64,
    'supports' : IDL.Vec(IDL.Float64),
    'patternType' : IDL.Text,
    'volume' : IDL.Float64,
    'openInterest' : IDL.Float64,
    'isMomentumBreakout' : IDL.Bool,
    'isInstitutionalEntry' : IDL.Bool,
    'recoveryStrength' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const Region = IDL.Record({
    'flowRatio' : IDL.Float64,
    'name' : IDL.Text,
    'volume' : IDL.Float64,
    'capitalFlow' : IDL.Float64,
    'countryCodes' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
    'regionId' : IDL.Nat,
    'intensity' : IDL.Float64,
    'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
  });
  const RegionalFlowConfig = IDL.Record({
    'name' : IDL.Text,
    'velocityMultiplier' : IDL.Float64,
    'countryCodes' : IDL.Vec(IDL.Text),
    'intensityMultiplier' : IDL.Float64,
    'regionId' : IDL.Nat,
    'coordinates' : IDL.Tuple(IDL.Float64, IDL.Float64),
  });
  const RegionalCorrelation = IDL.Record({
    'correlationStrength' : IDL.Float64,
    'timestamp' : Time,
    'regionId' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const RegionalCryptoAsset = IDL.Record({
    'marketCap' : IDL.Float64,
    'name' : IDL.Text,
    'liquidity' : IDL.Float64,
    'regionalVolume' : IDL.Float64,
    'usdValue' : IDL.Float64,
    'timestamp' : Time,
    'regionId' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const RegionalMetric = IDL.Record({
    'value' : IDL.Float64,
    'timestamp' : Time,
    'metricType' : IDL.Text,
    'regionId' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCapitalFlow' : IDL.Func(
        [
          IDL.Text,
          CryptoAsset,
          CryptoAsset,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'addConfluenceZone' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Float64],
        [],
        [],
      ),
    'addInstitutionalAlert' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'addModelPerformance' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'addPredictionOutcome' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'addPredictiveProjection' : IDL.Func(
        [
          IDL.Text,
          CryptoAsset,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Opt(IDL.Vec(TargetLevel)),
        ],
        [],
        [],
      ),
    'addRecoveryAsset' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Vec(IDL.Float64),
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'addRegion' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Tuple(IDL.Float64, IDL.Float64)],
        [],
        [],
      ),
    'addSummary' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addValidationResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearDailyAnalysis' : IDL.Func([IDL.Text], [], []),
    'clearOldStats' : IDL.Func([], [], []),
    'clearValidationResults' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAggregatedPredictions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AssetOutcomes)],
        ['query'],
      ),
    'getAlertConfig' : IDL.Func([IDL.Nat], [AlertConfig], ['query']),
    'getAllFlows' : IDL.Func([], [IDL.Vec(CapitalFlow)], ['query']),
    'getAllModelPerformances' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ModelPerformance)],
        ['query'],
      ),
    'getCachedPrices' : IDL.Func([], [IDL.Vec(PriceTicker)], ['query']),
    'getCachedSymbols' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCapitalFlow' : IDL.Func([IDL.Text], [CapitalFlow], ['query']),
    'getConfidenceMetrics' : IDL.Func(
        [IDL.Text],
        [ConfidenceMetrics],
        ['query'],
      ),
    'getConfluenceZone' : IDL.Func([IDL.Text], [ConfluenceZone], ['query']),
    'getDayFlowRange' : IDL.Func([IDL.Nat, IDL.Nat], [DayFlowRange], ['query']),
    'getInstitutionalAlerts' : IDL.Func(
        [],
        [IDL.Vec(InstitutionalAlert)],
        ['query'],
      ),
    'getInterpretation' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'direction' : IDL.Text,
            'summary' : IDL.Text,
            'intensity' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getModelPerformance' : IDL.Func(
        [IDL.Text, IDL.Text],
        [ModelPerformance],
        ['query'],
      ),
    'getPerformanceSummary' : IDL.Func(
        [IDL.Text],
        [PerformanceSummary],
        ['query'],
      ),
    'getPredictionOutcomes' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PredictionOutcome)],
        ['query'],
      ),
    'getPredictiveProjection' : IDL.Func(
        [IDL.Text],
        [PredictiveProjection],
        ['query'],
      ),
    'getRecoveryAsset' : IDL.Func([IDL.Text], [RecoveryAsset], ['query']),
    'getRegion' : IDL.Func([IDL.Nat], [Region], ['query']),
    'getRegionConfigs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, RegionalFlowConfig))],
        ['query'],
      ),
    'getRegionCoordinates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Tuple(IDL.Float64, IDL.Float64)))],
        ['query'],
      ),
    'getRegionalCorrelations' : IDL.Func(
        [],
        [IDL.Vec(RegionalCorrelation)],
        ['query'],
      ),
    'getRegionalCryptoAsset' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [RegionalCryptoAsset],
        ['query'],
      ),
    'getRegionalFlowConfig' : IDL.Func(
        [IDL.Nat],
        [RegionalFlowConfig],
        ['query'],
      ),
    'getRegionalMetric' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [RegionalMetric],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getValidationResults' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getValidationState' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCriticalAlertDay' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], ['query']),
    'printVolumeChanges' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDirection' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };