/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlertConfig {
  'updated_at' : Time,
  'criticalAlertDays' : Array<bigint>,
  'minVolumeThreshold' : number,
  'highPriorityAlertTypes' : Array<string>,
  'maxAlertFrequency' : bigint,
  'minIntensityThreshold' : number,
}
export interface AssetOutcomes {
  'assetSymbol' : string,
  'predictionOutcomes' : Array<PredictionOutcome>,
}
export type BinanceFuturesMarket = { 'usdt_m' : null } |
  { 'coin_m' : null };
export interface BubbleAsset {
  'trend' : string,
  'name' : string,
  'flowIntensity' : number,
  'confluenceIntensity' : number,
  'confidenceLevel' : number,
  'price' : number,
  'symbol' : string,
}
export interface BubbleAssetsResult {
  'count' : bigint,
  'lastUpdated' : Time,
  'bubbleAssets' : Array<BubbleAsset>,
}
export interface CapitalFlow {
  'marketImpact' : number,
  'flowIntensity' : number,
  'pnlRatio' : number,
  'timestamp' : Time,
  'amount' : number,
  'fromAsset' : CryptoAsset,
  'toAsset' : CryptoAsset,
}
export interface ConfidenceMetrics {
  'improvementRatio' : number,
  'averageConfidence' : number,
  'assetSymbol' : string,
  'accuracyImprovement' : number,
  'confidenceAccuracyCorrelation' : number,
}
export interface ConfluenceZone {
  'indicators' : Array<string>,
  'timestamp' : Time,
  'intensity' : number,
}
export interface CryptoAsset {
  'name' : string,
  'usdValue' : number,
  'symbol' : string,
}
export interface DayFlowRange {
  'startTime' : Time,
  'endTime' : Time,
  'flowData' : Array<RegionalFlow>,
}
export interface InstitutionalAlert {
  'intensityChange' : number,
  'type' : string,
  'alertId' : bigint,
  'volumeChange' : number,
  'timestamp' : Time,
  'regionId' : bigint,
}
export interface ModelPerformance {
  'performanceScore' : number,
  'confidenceCorrelation' : number,
  'validationResults' : Array<string>,
  'deviation' : number,
  'predictions' : Array<PredictionOutcome>,
  'assetSymbol' : string,
  'modelName' : string,
  'timestamp' : Time,
  'validationTime' : number,
  'accuracy' : number,
}
export interface NormalizedFuturesPosition {
  'pnl' : number,
  'markPrice' : number,
  'leverage' : number,
  'positionSide' : string,
  'liquidationPrice' : number,
  'entryPrice' : number,
  'market' : BinanceFuturesMarket,
  'symbol' : string,
  'positionAmt' : number,
}
export interface PerformanceSummary {
  'averageAccuracy' : number,
  'totalPredictions' : bigint,
  'validatedPredictions' : bigint,
  'assetSymbol' : string,
  'averageDeviation' : number,
  'lowestPerformer' : string,
  'highestPerformer' : string,
  'validationTime' : number,
}
export interface PredictionOutcome {
  'predictedValue' : number,
  'actualValue' : number,
  'confidence' : number,
  'outcome' : string,
}
export interface PredictiveProjection {
  'trend' : string,
  'asset' : CryptoAsset,
  'targetLevels' : Array<TargetLevel>,
  'confidenceLevel' : number,
  'precision' : number,
  'timeHorizon' : bigint,
}
export interface PriceTicker { 'price' : number, 'symbol' : string }
export interface RecoveryAsset {
  'rsi' : number,
  'supports' : Array<number>,
  'patternType' : string,
  'volume' : number,
  'openInterest' : number,
  'isMomentumBreakout' : boolean,
  'isInstitutionalEntry' : boolean,
  'recoveryStrength' : number,
  'symbol' : string,
}
export interface Region {
  'flowRatio' : number,
  'name' : string,
  'volume' : number,
  'capitalFlow' : number,
  'countryCodes' : Array<string>,
  'timestamp' : Time,
  'regionId' : bigint,
  'intensity' : number,
  'coordinates' : [number, number],
}
export interface RegionalCorrelation {
  'correlationStrength' : number,
  'timestamp' : Time,
  'regionId' : bigint,
  'symbol' : string,
}
export interface RegionalCryptoAsset {
  'marketCap' : number,
  'name' : string,
  'liquidity' : number,
  'regionalVolume' : number,
  'usdValue' : number,
  'timestamp' : Time,
  'regionId' : bigint,
  'symbol' : string,
}
export interface RegionalFlow {
  'velocity' : number,
  'toRegion' : bigint,
  'fromRegion' : bigint,
  'volume' : number,
  'timestamp' : Time,
  'correlations' : Array<[string, number]>,
  'intensity' : number,
}
export interface RegionalFlowConfig {
  'name' : string,
  'velocityMultiplier' : number,
  'countryCodes' : Array<string>,
  'intensityMultiplier' : number,
  'regionId' : bigint,
  'coordinates' : [number, number],
}
export interface RegionalMetric {
  'value' : number,
  'timestamp' : Time,
  'metricType' : string,
  'regionId' : bigint,
  'symbol' : string,
}
export interface TargetLevel {
  'priceLevel' : number,
  'source' : string,
  'confidenceScore' : number,
  'levelType' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'preferences' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCapitalFlow' : ActorMethod<
    [string, CryptoAsset, CryptoAsset, number, number, number, number],
    undefined
  >,
  'addConfluenceZone' : ActorMethod<[string, Array<string>, number], undefined>,
  'addInstitutionalAlert' : ActorMethod<
    [bigint, bigint, string, number, number],
    undefined
  >,
  'addModelPerformance' : ActorMethod<
    [string, string, number, number, number, number, number],
    undefined
  >,
  'addOrUpdateBinanceCredentials' : ActorMethod<[string, string], undefined>,
  'addPredictionOutcome' : ActorMethod<
    [string, number, number, number, string],
    undefined
  >,
  'addPredictiveProjection' : ActorMethod<
    [
      string,
      CryptoAsset,
      string,
      number,
      number,
      bigint,
      [] | [Array<TargetLevel>],
    ],
    undefined
  >,
  'addRecoveryAsset' : ActorMethod<
    [
      string,
      number,
      string,
      number,
      number,
      number,
      Array<number>,
      boolean,
      boolean,
    ],
    undefined
  >,
  'addRegion' : ActorMethod<[bigint, string, [number, number]], undefined>,
  'addSummary' : ActorMethod<[string, string], undefined>,
  'addValidationResult' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearDailyAnalysis' : ActorMethod<[string], undefined>,
  'clearOldStats' : ActorMethod<[], undefined>,
  'clearValidationResults' : ActorMethod<[string, string], undefined>,
  'getAggregatedPredictions' : ActorMethod<[string], Array<AssetOutcomes>>,
  'getAlertConfig' : ActorMethod<[bigint], AlertConfig>,
  'getAllFlows' : ActorMethod<[], Array<CapitalFlow>>,
  'getAllModelPerformances' : ActorMethod<[string], Array<ModelPerformance>>,
  'getBubbleAssets' : ActorMethod<[], BubbleAssetsResult>,
  'getCachedPrices' : ActorMethod<[], Array<PriceTicker>>,
  'getCachedSymbols' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCapitalFlow' : ActorMethod<[string], CapitalFlow>,
  'getConfidenceMetrics' : ActorMethod<[string], ConfidenceMetrics>,
  'getConfluenceZone' : ActorMethod<[string], ConfluenceZone>,
  'getDayFlowRange' : ActorMethod<[bigint, bigint], DayFlowRange>,
  'getInstitutionalAlerts' : ActorMethod<[], Array<InstitutionalAlert>>,
  'getInterpretation' : ActorMethod<
    [string],
    { 'direction' : string, 'summary' : string, 'intensity' : number }
  >,
  'getModelPerformance' : ActorMethod<[string, string], ModelPerformance>,
  'getOpenFuturesPositions' : ActorMethod<[], Array<NormalizedFuturesPosition>>,
  'getPerformanceSummary' : ActorMethod<[string], PerformanceSummary>,
  'getPredictionOutcomes' : ActorMethod<[string], Array<PredictionOutcome>>,
  'getPredictiveProjection' : ActorMethod<[string], PredictiveProjection>,
  'getRecoveryAsset' : ActorMethod<[string], RecoveryAsset>,
  'getRegion' : ActorMethod<[bigint], Region>,
  'getRegionConfigs' : ActorMethod<[], Array<[bigint, RegionalFlowConfig]>>,
  'getRegionCoordinates' : ActorMethod<[], Array<[bigint, [number, number]]>>,
  'getRegionalCorrelations' : ActorMethod<[], Array<RegionalCorrelation>>,
  'getRegionalCryptoAsset' : ActorMethod<[bigint, string], RegionalCryptoAsset>,
  'getRegionalFlowConfig' : ActorMethod<[bigint], RegionalFlowConfig>,
  'getRegionalMetric' : ActorMethod<[bigint, string], RegionalMetric>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getValidationResults' : ActorMethod<[string, string], Array<string>>,
  'getValidationState' : ActorMethod<[string], bigint>,
  'hasBinanceCredentials' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCriticalAlertDay' : ActorMethod<[bigint, bigint], boolean>,
  'printVolumeChanges' : ActorMethod<[], undefined>,
  'removeBinanceCredentials' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'testBinanceConnection' : ActorMethod<[], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateDirection' : ActorMethod<[string, string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];